name: hf
dependencies:
  - python==3.9
  - pip
  - conda 
  - pip:
    - pandas
    - numpy
    - transformers
    - datasets
    - bertopic
    - seaborn
    - ipywidgets
    - kaleido
    - python-dotenv
  - conda:
    - ipykernel